---
apiVersion: v1
kind: Secret
metadata:
  name: admin-credential
type: Opaque
stringData:
  password: password
---
apiVersion: v1
kind: Secret
metadata:
  name: preview-readonly-minimal-credential
type: Opaque
stringData:
  password: password
---
apiVersion: v1
kind: Secret
metadata:
  name: preview-readwrite-credential
type: Opaque
stringData:
  password: password