---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: preview-mongodb
spec:
  members: 1
  type: ReplicaSet
  version: "6.0.5"
  security:
    authentication:
      modes: ["SCRAM"]
    roles: # custom roles are defined here
      - role: dbTestReadOnly
        db: test
        privileges:
          - resource:
              db: "test"
              collection: "" # an empty string indicates any collection
            actions:
              - find
        roles: []
  users:
    - name: admin
      db: admin
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password. One we created earlier
        name: admin-credential
      connectionStringSecretName: admin-connection-string
      roles:
        - name: clusterAdmin
          db: admin
        - name: userAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
        - name: dbAdminAnyDatabase
          db: admin
      scramCredentialsSecretName: admin-scram
    - name: preview-readonly-minimal
      db: test
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: preview-readonly-minimal-credential
      connectionStringSecretName: preview-readonly-minimal-connection-string
      roles:
        - name: dbTestReadOnly
          db: test
      scramCredentialsSecretName: preview-readonly-minimal-scram
    - name: preview-readwrite
      db: test
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password
        name: preview-readwrite-credential
      connectionStringSecretName: preview-backend-readwrite-connection-string
      roles:
        - name: readWrite
          db: test
      scramCredentialsSecretName: preview-backend-readwrite-scram
  additionalMongodConfig:
    storage.wiredTiger.engineConfig.journalCompressor: zlib
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: 
              - "ReadWriteOnce"
            resources:
              requests:
                storage: 3Gi
        - metadata:
            name: logs-volume
          spec:
            accessModes: 
              - "ReadWriteOnce"
            resources:
              requests:
                storage: 512Mi
      template:
        spec:
          containers:
            - name: mongodb-agent
              readinessProbe:
                failureThreshold: 40
                initialDelaySeconds: 5

# the user credentials will be generated from this secret
# once the credentials are generated, this secret is no longer required
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-password
type: Opaque
stringData:
  password: password