services:
  typesense:
    image: typesense/typesense:26.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=jxhui --enable-cors --enable-search-analytics --analytics-dir=./typesense-analytics'
